AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/devise.rb'

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10

Rails:
  Enabled: true

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation


Style/ClassVars:
  Exclude:
    - 'spec/support/shared_connections.rb'

Style/Documentation:
  Enabled: false

Style/ExtraSpacing:
  Exclude:
    - 'bin/*'

Style/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - 'Rakefile'
    - 'lib/tasks/*.rake'
    - 'tasks/*.rake'

Style/IfUnlessModifier:
  Enabled: false

Style/IndentArray:
  EnforcedStyle: consistent

Style/IndentHash:
  Enabled: consistent

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  ()
    '%i': '[]'
    '%q': ()
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': '[]'
    '%W': '[]'
    '%x': ()

Style/StringLiterals:
  Exclude:
    - 'bin/*'
