redis: &redis
  adapter: redis

production:
  url: redis://redistogo:575b78ca1e7be9c87c5461d456429ced@porgy.redistogo.com:9983/

  <<: *redis
development:
  url: redis://localhost:6379

  <<: *redis
test:
  <<: *redis
